import React, { useState, useEffect } from 'react';
import { View, StyleSheet, ScrollView, Alert } from 'react-native';
import { Button, Text, Card, ActivityIndicator, IconButton, Divider } from 'react-native-paper';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { RootStackParamList } from '../../App';
import apiClient from '../services/api';
import { ENDPOINTS } from '../config/api';
import { Itinerary, DailyPlan } from '../types';

type Props = NativeStackScreenProps<RootStackParamList, 'Itinerary'>;

export default function ItineraryScreen({ navigation, route }: Props) {
  const { itineraryId } = route.params;
  const [itinerary, setItinerary] = useState<Itinerary | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadItinerary();
  }, []);

  const loadItinerary = async () => {
    try {
      const response = await apiClient.get<Itinerary>(
        ENDPOINTS.GET_ITINERARY_BY_ID(itineraryId)
      );
      setItinerary(response.data);
    } catch (error: any) {
      Alert.alert('Error', error.response?.data?.detail || 'Failed to load itinerary');
      navigation.goBack();
    } finally {
      setLoading(false);
    }
  };

  const handleRating = async (helpful: boolean) => {
    if (!itinerary) return;

    try {
      await apiClient.patch(ENDPOINTS.RATE_ITINERARY(itinerary.id), { helpful });
      setItinerary({ ...itinerary, helpful_rating: helpful ? 'helpful' : 'not_helpful' });
      Alert.alert('Thank You', 'Your feedback helps us improve!');
    } catch (error) {
      console.error('Failed to rate itinerary:', error);
    }
  };

  if (loading) {
    return (
      <View style={styles.loadingContainer}>
        <ActivityIndicator size="large" color="#8B5CF6" />
        <Text variant="bodyLarge" style={styles.loadingText}>
          Loading your itinerary...
        </Text>
      </View>
    );
  }

  if (!itinerary) {
    return null;
  }

  return (
    <ScrollView style={styles.container}>
      {/* CRITICAL: AI Disclosure Banner - REQUIRED by Apple Guidelines */}
      <View style={styles.aiDisclosureBanner}>
        <Text variant="bodyMedium" style={styles.aiDisclosureText}>
          ⚠️ This itinerary was generated by AI
        </Text>
      </View>

      {/* Header */}
      <View style={styles.header}>
        <Text variant="headlineMedium" style={styles.cityName}>
          {itinerary.city_name}, {itinerary.country}
        </Text>
        <Text variant="bodyMedium" style={styles.tripLength}>
          {itinerary.trip_length_days}-Day Trip
        </Text>
      </View>

      {/* General Tips */}
      {itinerary.itinerary_data.general_tips && (
        <Card style={styles.tipsCard}>
          <Card.Content>
            <Text variant="titleMedium" style={styles.tipsTitle}>
              💡 General Tips
            </Text>
            {itinerary.itinerary_data.general_tips.map((tip, index) => (
              <Text key={index} variant="bodyMedium" style={styles.tip}>
                • {tip}
              </Text>
            ))}
          </Card.Content>
        </Card>
      )}

      {/* Daily Plans */}
      {itinerary.itinerary_data.daily_plans.map((day: DailyPlan) => (
        <Card key={day.day} style={styles.dayCard}>
          <Card.Content>
            <Text variant="titleLarge" style={styles.dayTitle}>
              Day {day.day}
            </Text>

            {/* Morning */}
            <View style={styles.timeSection}>
              <Text variant="titleMedium" style={styles.timeTitle}>
                🌅 Morning
              </Text>
              <Text variant="bodyMedium" style={styles.activityText}>
                {day.morning.activity}
              </Text>
              <Text variant="bodySmall" style={styles.detailText}>
                📍 {day.morning.location}
              </Text>
              <Text variant="bodySmall" style={styles.detailText}>
                ⏱️ {day.morning.duration}
              </Text>
              <Text variant="bodySmall" style={styles.tipsText}>
                💡 {day.morning.tips}
              </Text>
            </View>

            <Divider style={styles.divider} />

            {/* Lunch */}
            <View style={styles.timeSection}>
              <Text variant="titleMedium" style={styles.timeTitle}>
                🍽️ Lunch
              </Text>
              <Text variant="bodyMedium" style={styles.activityText}>
                {day.lunch.restaurant}
              </Text>
              <Text variant="bodySmall" style={styles.detailText}>
                🍴 {day.lunch.cuisine} • {day.lunch.price_range}
              </Text>
              <Text variant="bodySmall" style={styles.detailText}>
                📍 {day.lunch.neighborhood}
              </Text>
            </View>

            <Divider style={styles.divider} />

            {/* Afternoon */}
            <View style={styles.timeSection}>
              <Text variant="titleMedium" style={styles.timeTitle}>
                ☀️ Afternoon
              </Text>
              <Text variant="bodyMedium" style={styles.activityText}>
                {day.afternoon.activity}
              </Text>
              <Text variant="bodySmall" style={styles.detailText}>
                📍 {day.afternoon.location}
              </Text>
              <Text variant="bodySmall" style={styles.detailText}>
                ⏱️ {day.afternoon.duration}
              </Text>
              <Text variant="bodySmall" style={styles.tipsText}>
                💡 {day.afternoon.tips}
              </Text>
            </View>

            <Divider style={styles.divider} />

            {/* Dinner */}
            <View style={styles.timeSection}>
              <Text variant="titleMedium" style={styles.timeTitle}>
                🌙 Dinner
              </Text>
              <Text variant="bodyMedium" style={styles.activityText}>
                {day.dinner.restaurant}
              </Text>
              <Text variant="bodySmall" style={styles.detailText}>
                🍴 {day.dinner.cuisine} • {day.dinner.price_range}
              </Text>
              <Text variant="bodySmall" style={styles.detailText}>
                📍 {day.dinner.neighborhood}
              </Text>
            </View>

            {/* Evening (Optional) */}
            {day.evening && (
              <>
                <Divider style={styles.divider} />
                <View style={styles.timeSection}>
                  <Text variant="titleMedium" style={styles.timeTitle}>
                    ✨ Evening {day.evening.optional && '(Optional)'}
                  </Text>
                  <Text variant="bodyMedium" style={styles.activityText}>
                    {day.evening.activity}
                  </Text>
                </View>
              </>
            )}
          </Card.Content>
        </Card>
      ))}

      {/* Rating */}
      <View style={styles.ratingSection}>
        <Text variant="titleMedium" style={styles.ratingTitle}>
          Was this itinerary helpful?
        </Text>
        <View style={styles.ratingButtons}>
          <IconButton
            icon="thumb-up"
            size={32}
            iconColor={itinerary.helpful_rating === 'helpful' ? '#10B981' : '#666666'}
            onPress={() => handleRating(true)}
          />
          <IconButton
            icon="thumb-down"
            size={32}
            iconColor={itinerary.helpful_rating === 'not_helpful' ? '#EF4444' : '#666666'}
            onPress={() => handleRating(false)}
          />
        </View>
      </View>

      {/* Feedback Button */}
      <Button
        mode="outlined"
        onPress={() => navigation.navigate('Feedback', { itineraryId })}
        style={styles.feedbackButton}
        icon="flag"
      >
        Report an Issue
      </Button>

      {/* Home Button */}
      <Button
        mode="contained"
        onPress={() => navigation.navigate('Preferences')}
        style={styles.homeButton}
        contentStyle={styles.buttonContent}
      >
        Create New Itinerary
      </Button>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  loadingText: {
    marginTop: 16,
    color: '#666666',
  },
  aiDisclosureBanner: {
    backgroundColor: '#FFF7ED',
    borderLeftWidth: 4,
    borderLeftColor: '#F59E0B',
    padding: 16,
    marginBottom: 16,
  },
  aiDisclosureText: {
    color: '#92400E',
    fontWeight: '600',
  },
  header: {
    paddingHorizontal: 24,
    paddingTop: 16,
    marginBottom: 24,
  },
  cityName: {
    fontWeight: 'bold',
    marginBottom: 8,
  },
  tripLength: {
    color: '#666666',
  },
  tipsCard: {
    marginHorizontal: 24,
    marginBottom: 16,
    backgroundColor: '#EFF6FF',
  },
  tipsTitle: {
    fontWeight: 'bold',
    marginBottom: 12,
  },
  tip: {
    marginBottom: 8,
    color: '#1E40AF',
  },
  dayCard: {
    marginHorizontal: 24,
    marginBottom: 16,
  },
  dayTitle: {
    fontWeight: 'bold',
    marginBottom: 16,
    color: '#8B5CF6',
  },
  timeSection: {
    marginBottom: 16,
  },
  timeTitle: {
    fontWeight: 'bold',
    marginBottom: 8,
  },
  activityText: {
    marginBottom: 4,
    fontWeight: '600',
  },
  detailText: {
    color: '#666666',
    marginBottom: 2,
  },
  tipsText: {
    color: '#8B5CF6',
    marginTop: 4,
    fontStyle: 'italic',
  },
  divider: {
    marginVertical: 12,
  },
  ratingSection: {
    alignItems: 'center',
    paddingHorizontal: 24,
    marginTop: 16,
    marginBottom: 16,
  },
  ratingTitle: {
    marginBottom: 12,
  },
  ratingButtons: {
    flexDirection: 'row',
    gap: 24,
  },
  feedbackButton: {
    marginHorizontal: 24,
    marginBottom: 16,
    borderColor: '#8B5CF6',
  },
  homeButton: {
    marginHorizontal: 24,
    marginBottom: 40,
    backgroundColor: '#8B5CF6',
  },
  buttonContent: {
    paddingVertical: 8,
  },
});
