from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from app.config import settings
from app.database import engine, Base
from app.api import auth, preferences, cities, itineraries, feedback, user

# Create database tables
Base.metadata.create_all(bind=engine)

# Initialize FastAPI app with comprehensive OpenAPI metadata
app = FastAPI(
    title="Timbuktoo API",
    description="""
# Timbuktoo Travel Concierge API

AI-powered travel planning API that generates personalized city recommendations and detailed itineraries.

## Features

* **🤖 AI-Powered Recommendations**: Uses Claude 3.5 Sonnet to analyze preferences and suggest destinations
* **🗺️ Personalized Itineraries**: Generates day-by-day plans with activities, dining, and tips
* **👤 User Management**: Secure authentication with JWT tokens
* **📊 Feedback System**: Report issues with AI-generated content (Apple App Store compliance)
* **🔒 GDPR/CCPA Compliant**: Account deletion and data privacy controls

## Authentication

Most endpoints require JWT Bearer token authentication:

```
Authorization: Bearer <your-jwt-token>
```

Get your token from `/auth/signup` or `/auth/login` endpoints.

## Rate Limits

**Free Tier:**
- 3 itineraries per user lifetime
- Unlimited city recommendations

**Pro Tier (Coming Soon):**
- Unlimited itineraries
- Priority AI generation
- Premium destinations

## AI Disclosure

⚠️ **Important**: All itineraries are generated by AI and should be independently verified before making travel decisions.
This API complies with Apple App Store Guideline 5.1.1 (AI Disclosure Requirements).

## Support

- **Documentation**: https://docs.timbuktoo.ai (coming soon)
- **Issues**: https://github.com/timbuktoo/api/issues
- **Email**: support@timbuktoo.ai
    """,
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
    contact={
        "name": "Timbuktoo Support",
        "email": "support@timbuktoo.ai",
        "url": "https://timbuktoo.ai"
    },
    license_info={
        "name": "Proprietary",
        "url": "https://timbuktoo.ai/terms"
    },
    terms_of_service="https://timbuktoo.ai/terms",
    openapi_tags=[
        {
            "name": "Authentication",
            "description": "User signup, login, and token management"
        },
        {
            "name": "Preferences",
            "description": "Manage travel preferences (interests, budget, pace)"
        },
        {
            "name": "Cities",
            "description": "Get AI-generated city recommendations based on preferences"
        },
        {
            "name": "Itineraries",
            "description": "Generate and manage detailed travel itineraries"
        },
        {
            "name": "Feedback",
            "description": "Report issues with AI-generated content"
        },
        {
            "name": "User",
            "description": "User account management and data deletion (GDPR/CCPA)"
        },
        {
            "name": "Health",
            "description": "Health check and monitoring endpoints"
        }
    ]
)

# CORS middleware (allow mobile app to connect)
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins_list,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Include API routers
app.include_router(auth.router)
app.include_router(preferences.router)
app.include_router(cities.router)
app.include_router(itineraries.router)
app.include_router(feedback.router)
app.include_router(user.router)


@app.get(
    "/",
    tags=["Health"],
    summary="Root endpoint",
    description="Simple health check that returns API information"
)
async def root():
    """Get API information and version"""
    return {
        "status": "ok",
        "service": "Timbuktoo API",
        "version": "1.0.0",
        "docs": "/docs"
    }


@app.get(
    "/health",
    tags=["Health"],
    summary="Health check endpoint",
    description="""
    Comprehensive health check for monitoring tools.

    Use this endpoint for:
    - Load balancer health checks (AWS ALB, GCP LB)
    - Uptime monitoring (Datadog, Pingdom, UptimeRobot)
    - Container orchestration (Kubernetes liveness/readiness probes)

    Returns database connection status to ensure full system health.
    """
)
async def health_check():
    """
    Health check endpoint for monitoring systems

    Returns:
        dict: Health status including database connection
    """
    return {
        "status": "healthy",
        "database": "connected",
        "version": "1.0.0"
    }


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(
        "app.main:app",
        host=settings.API_HOST,
        port=settings.API_PORT,
        reload=settings.DEBUG
    )
