from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from app.database import get_db
from app.models.user import User
from app.models.preference import Preference
from app.models.itinerary import Itinerary
from app.models.subscription import Subscription
from app.schemas.itinerary import ItineraryRequest, ItineraryResponse
from app.utils.auth import get_current_user
from app.utils.anthropic_client import generate_itinerary, AI_MODEL, PROMPT_VERSION
from app.config import settings
from typing import List

router = APIRouter(prefix="/itinerary", tags=["Itineraries"])


@router.post("/generate", response_model=ItineraryResponse, status_code=status.HTTP_201_CREATED)
async def generate_new_itinerary(
    request: ItineraryRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Generate a new AI-powered itinerary for a specific city

    CRITICAL: This is AI-generated content. The mobile app MUST display the
    AI banner: "⚠️ This itinerary was generated by AI" on the ItineraryScreen.

    Rate Limiting (Free Tier):
    - Free users: 3 itineraries per month
    - Pro users: Unlimited itineraries

    Generation Time: 30-60 seconds (show loading indicator in mobile app)
    """

    # Check rate limiting for free tier users
    subscription = db.query(Subscription).filter(
        Subscription.user_id == current_user.id,
        Subscription.status == "active"
    ).first()

    if subscription and subscription.tier == "free":
        # Count itineraries created this month
        itinerary_count = db.query(Itinerary).filter(
            Itinerary.user_id == current_user.id
        ).count()

        if itinerary_count >= settings.FREE_TIER_ITINERARY_LIMIT:
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail=f"Free tier limit reached. You've generated {itinerary_count}/{settings.FREE_TIER_ITINERARY_LIMIT} itineraries this month. Upgrade to Pro for unlimited itineraries."
            )

    # Get user's preferences
    preference = db.query(Preference).filter(
        Preference.user_id == current_user.id
    ).first()

    if not preference:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Please set your travel preferences first"
        )

    # Generate itinerary using Concierge Agent
    try:
        itinerary_data = await generate_itinerary(
            city_name=request.city_name,
            country=request.country,
            trip_length_days=request.trip_length_days,
            interests=preference.interests or [],
            food_preferences=preference.food_preferences or [],
            budget_level=preference.budget_level or "mid-range",
            pace=preference.pace or "moderate"
        )

        # Save itinerary to database
        new_itinerary = Itinerary(
            user_id=current_user.id,
            city_name=request.city_name,
            country=request.country,
            itinerary_data=itinerary_data,
            trip_length_days=request.trip_length_days,
            ai_model=AI_MODEL,
            prompt_version=PROMPT_VERSION
        )

        db.add(new_itinerary)
        db.commit()
        db.refresh(new_itinerary)

        return ItineraryResponse.from_orm(new_itinerary)

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to generate itinerary: {str(e)}"
        )


@router.get("", response_model=List[ItineraryResponse])
async def get_user_itineraries(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
    limit: int = 20
):
    """
    Retrieve all itineraries for the current user

    Returns itineraries ordered by creation date (most recent first)
    """

    itineraries = db.query(Itinerary).filter(
        Itinerary.user_id == current_user.id
    ).order_by(Itinerary.created_at.desc()).limit(limit).all()

    return [ItineraryResponse.from_orm(it) for it in itineraries]


@router.get("/{itinerary_id}", response_model=ItineraryResponse)
async def get_itinerary_by_id(
    itinerary_id: str,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Retrieve a specific itinerary by ID

    Only the itinerary owner can access it.
    """

    itinerary = db.query(Itinerary).filter(
        Itinerary.id == itinerary_id,
        Itinerary.user_id == current_user.id
    ).first()

    if not itinerary:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Itinerary not found"
        )

    return ItineraryResponse.from_orm(itinerary)


@router.patch("/{itinerary_id}/rating")
async def rate_itinerary(
    itinerary_id: str,
    helpful: bool,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Rate an itinerary as helpful or not helpful

    This feedback is used to improve AI recommendations.
    """

    itinerary = db.query(Itinerary).filter(
        Itinerary.id == itinerary_id,
        Itinerary.user_id == current_user.id
    ).first()

    if not itinerary:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Itinerary not found"
        )

    itinerary.helpful_rating = "helpful" if helpful else "not_helpful"
    db.commit()

    return {"status": "success", "helpful_rating": itinerary.helpful_rating}
